cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views

app_name="cart"
urlpatterns = [
    path('add_to_cart/<int:b>/',views.add_to_cart,name='add_to_cart'),
    path("cartview",views.cartview,name="cartview"),
    path('cart_remove/<int:p>/', views.cart_remove, name='cart_remove'),
    path('cart_delete/<int:p>/', views.cart_delete, name='cart_delete'),
    path("orderform", views.orderform, name="orderform"),
    path("orderview", views.orderview, name="orderview"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('shop.urls')),
    path("search/",include('search.urls')),
    path("cart/", include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views

app_name='search'
urlpatterns = [
    path('',views.searchresults,name="searchresults"),

]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views

app_name='shop'
urlpatterns = [
    path('',views.allprodcat,name="allprodcat"),
    path('products/<slug:p>', views.allproducts, name="allproducts"),
    path('alldetails/<slug:s>', views.alldetails, name="alldetails"),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout', views.user_logout, name="logout"),

]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User


class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

    def __str__(self):
        return self.product.name


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    noofitems=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def subtotal(self):
        return self.noofitems*self.product.price

    def __str__(self):
        return self.user.username


class Account(models.Model):
    acctnumber=models.CharField(max_length=30)
    acctype=models.CharField(max_length=30)
    amount=models.IntegerField()

    def __str__(self):
        return self.acctnumber

search/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='shop/category',null=True,blank=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='shop/category',null=True,blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from cart.models import Cart,Account,Order
@login_required
def cartview(request):
    total=0
    user=request.user
    try:
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.product.price
    except Cart.DoesNotExist:
        pass
    return render(request,'cartview.html',{'cart':cart,'total':total})
@login_required

def add_to_cart(request,b):
    b=Product.objects.get(id=b)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=b)
        if(cart.quantity<cart.product.stock):
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,product=b,quantity=1)
        cart.save()


    return redirect('cart:cartview')
@login_required

def cart_remove(request,p):
    p=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=p)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')
@login_required

def cart_delete(request,p):
    p=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(user=user,product=p)
        cart.delete()
    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')

@login_required

def orderform(request):
    total=0
    if(request.method=='POST'):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.product.price
        ac=Account.objects.get(acctnumber=n)
        if(ac.amount>=total):
            ac.amount=ac.amount-total
            ac.save()
            for i in cart:
                o=Order.objects.create(user=user,product=i.product,address=a,phone=p,order_status="paid",noofitems=i.quantity)
                o.save()
                i.product.stock=i.product.stock-i.quantity
                i.product.save()
            cart.delete()
            msg="Order placed successfully"
            return  render(request,'orderdetail.html',{'msg':msg})
        else:
            msg = "Insufficient amount.You cannot place the order"
            return render(request, 'orderdetail.html', {'msg': msg})

    return render(request,'orderform.html')

@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u,order_status='paid')
    return render(request,'orderview.html',{'o':o,'u':u.username})

search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q

def searchresults(request):
    query=""
    product=None
    if(request.method=="POST"):
        query=request.POST['q']
        print(query)
        if(query):
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'products':products,'query':query})

shop/views.py
from django.shortcuts import render
from shop.models import Category,Product
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages

from django.contrib.auth.decorators import login_required
def allprodcat(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(slug=p)
    p=Product.objects.filter(category__slug=p)
    return render(request,'product.html',{'p':p,'c':c})

def alldetails(request,s):
    b=Product.objects.get(slug=s)
    return render(request,'details.html',{'b':b})

def register(request):
    if (request.method=="POST"):
        u=request.POST['u']
        f=request.POST['f']
        l=request.POST['l']
        e=request.POST['e']
        p=request.POST['p']
        cp=request.POST['cp']
        if p==cp:
          user=User.objects.create_user(username=u,first_name=f,last_name=l,email=e,password=p)
          user.save()
        return user_login(request)
    return render(request,'register.html')
def user_login(request):
    if (request.method == "POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return allprodcat(request)
        else:
            messages.error(request,"invalid credentials")
    return render(request,'login.html')
def user_logout(request):
    logout(request)
    return allprodcat(request)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script crossorigin="anonymous"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link crossorigin href="https://fonts.gstatic.com" rel="preconnect">
    <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          referrerpolicy="no-referrer" rel="stylesheet"/>
</head>
<body class="pink">
<div class="container-fluid">
    <header>
        <center>
            <img height="100px" src="{% static 'images/logo3.jpg' %}" width="100px">
        </center>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">MyShop</a>
                <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                        class="navbar-toggler" data-bs-target="#navbarSupportedContent"
                        data-bs-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a aria-current="page" class="nav-link active" href="{% url 'shop:allprodcat' %}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                               id="navbarDropdown" role="button">
                                Shop
                            </a>
                            <ul aria-labelledby="navbarDropdown" class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">All Categories</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                {% for i in links %}
                                <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a>
                                </li>
                                {% endfor %}
                            </ul>
                            {% if user.is_authenticated %}
                            {% if user.username != 'admin' %}
                        </li>
                        <li class="nav-item">
                            <a aria-current="page" class="nav-link active" href="{% url 'cart:cartview' %}"><i
                                    class="fa-solid fa-cart-shopping"></i>{{count}}</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a aria-current="page" class="nav-link active" href="{% url 'cart:orderview' %}">Your
                                Orders</a>
                        </li>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            <a aria-current="page" class="nav-link active" href="{% url 'shop:logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a aria-current="page" class="nav-link active" href="{% url 'shop:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a aria-current="page" class="nav-link active" href="{% url 'shop:login' %}">Login</a>
                        </li>
                        {% endif %}

                    </ul>
                    <form action="{% url 'search:searchresults' %}" class="d-flex" method="POST">
                        {% csrf_token %}
                        <input aria-label="Search" class="form-control me-2" name="q" placeholder="Search"
                               type="search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
</div>
{% block content %}
{% endblock %}
<footer class="footer">
    <div>
        <p>
        <center><i class="fa-solid fa-copyright icon_size" style="font-size:12px">My Shop pvt ltd.All Rights
            Reserved</i></center>
        </p>
    </div>
</footer>
</body>
</html>

templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if not cart %}
<div>
    <h1 class="text-center">Cart is empty</h1>
    <strong><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></strong>
</div>
{% else %}
<div class="row">
    <h2 class="text-center">SHOPPING CART</h2>
    <div class="col-sm-6">
        <table class="table table-bordered">
            <tr>
                <th colspan="5">CART ITEMS</th>
            </tr>
            {% for i in cart %}
            <tr>
            <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
             <td><p><strong>{{i.product.name}}</strong></p></td>
                <td><p><strong>Product Id:{{i.product.id}}</strong></p>
             <p><strong>Unit Price:{{i.product.price}}</strong></p>
             <p><strong>Quantity:{{i.quantity}}*{{i.product.price}}</strong></p>
                </td>
                <td><p>Subtotal:{{i.subtotal}}</p></td>
                <td>
                    {% if i.quantity < i.product.stock %}
                    <a href="{% url 'cart:add_to_cart' i.product.id %}"><i class="fa-solid fa-circle-plus"></i></a>
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
                    {% else %}
                    <a href="{% url 'cart:cart_remove' i.product.id %}"><i class="fa-solid fa-circle-minus"></i></a>
                    <a href="{% url 'cart:cart_delete' i.product.id %}"><i class="fa-solid fa-trash"></i></a>
                    {% endif %}
                </td>
        </tr>
            {% endfor %}
        </table>
            </div>
        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr class="text-center">
                    <th colspan="5">CHECK OUT</th>
                </tr>
                <tr class="text-center">
                    <td>Total Amount:{{total}}</td>
                </tr>
            </table>
            <a href="{% url 'cart:orderform' %}" class="btn btn-primary">Place order</a>
            <a href="{% url 'shop:allprodcat' %}" style="position:absolute;right:0;" class="btn btn-primary">Continue Shopping</a>
        </div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{% static 'images/banner2.jpg' %}" height="450px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center mb-2">Our Collections</h3>
    <p class="text-justify" style="line-height:2; text-align:justify;">One simplifies everyday interactions. It's a free, contactless service that lets you use your palm to pay, enter, or identify yourself. A quick and easy way to make a payment, enter a venue, or identify yourself.
        Sign up once, then use wherever my shop is available.Pre-enroll onlineStart by signing up online using your My shop account. Visit an My shop location Find a location near you.

</p>

</div>

<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
        <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:250px;width:100%;">
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'shop:allproducts' i.slug %}" style="position:relative;left:38%" class="btn btn-primary">Products</a>
  </div>
</div>
        </div>
    {% endfor %}
</div>
        </div>

{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid">
    <div class="row">
<div class="col-md-4">
    <img src="{{b.image.url}}" style="float:left;margin:50px; height:400px;width:100%;">
</div>
<div class="col-md-7" style="padding-left:150px;padding-top:35px;">
    <div class="card-body">
    <h3 class="card-title">{{b.name}}</h3>
        <p class="card-text">{{b.price}}</p>
        <h3 class="card-text">Product Description</h3>
    <p class="card-text">{{b.description}}</p>
        {% if user.username != 'admin' %}
        {% if b.stock <= 0 %}
        <h4>Out of Stock</h4>
        {% else %}
    <a href="{% url 'cart:add_to_cart' b.id %}" style="position:relative;left:38%" class="btn btn-primary">Add to Cart</a>
        {% endif %}
        {% else %}
            {% if p.stock <= 0 %}
                <h4>Out Of Stock</h4>
                <a href="{% url 'admin:index' %}">ADD STOCK</a>
            {% endif %}
        {% endif %}
</div>
    </div>
</div>
</div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px;">
<form method="POST" enctype="multipart/form-data" class="border border-3 border-primary bg-secondary">
    {% csrf_token %}
    <div class="m-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
    </div>
<div class="m-3">
  <label class="form-label">password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
    </div>
    <div class="mb-3">
  <input type="submit" value="Login" style="margin-left:15px;">
    </div>
  </form>
  {% if messages %}
  {% for i in messages %}
  <ul class="messages">
    <li>{{i}}</li>
  </ul>
    {% endfor %}
  {% endif %}
</div>
{% endblock %}

templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}add{% endblock %}
{% block content %}
<div class="container">
    <h2 class="text-center text-success">{{msg}}</h2>
    <h5 class="text-center text-danger">Thank you.....</h5>
    <p class="text-center"><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a></p>
</div>

{% endblock %}

templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<form method="POST">
          {% csrf_token %}
<div class="container">

<div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="Enter Address">
</div>
    <div class="mb-3">
  <label class="form-label">Phone Number</label>
  <input type="number" class="form-control" name="p" placeholder="Enter phone number">
</div>
    <div class="mb-3">
  <label class="form-label">Account Number</label>
  <input type="number" class="form-control" name="n"  placeholder="Enter Acc number">
</div>
<div class="mb-3">
<input type="submit" class="btn btn-primary form-control">
</div>
    </div>
    </form>
{% endblock %}

templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block title %}add{% endblock %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
  <div class="row">
    <h5 class="text-center">Name of the customer::{{u}}</h5>
    {% for i in o %}
    <div class="col-sm-3 py-3" style="border:2px solid grey">
      <center>
      <img src="{{i.product.image.url}}" height="200px" width="150px"></center>
    </div>
    <div class="col-sm-7 text-center" style="border:2px solid grey">
      Delivery Address:{{i.address}}<br>
      Phone Number:{{i.phone}}<br>
      {{i.product.name}}<br>
      {{i.product.price}}<br>
      Quantity Ordered:{{i.noofitems}}<br>
      Subtotal:{{i.subtotal}}<br>
      <strong class="text-primary">Ordered on{{i.date_added}}</strong>
      <strong class="text-success">Delivery Status{{i.delivery_status}}</strong>
    </div>
     {% endfor %}
      </div>
</div>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img src="{{c.image.url}}" height="450px" width="100%">
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <h3 class="text-center mb-2">{{c.name}}</h3>
    <p class="text-justify" style="line-height:2; text-align:justify;">{{c.description}}</p>

</div>

<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
        <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:400px;width:100%;">
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <h5 class="card-text text-center" style="text-align:justify">{{i.price}}</h5>
    <a href="{% url 'shop:alldetails' i.slug %}" style="position:relative;left:38%" class="btn btn-primary">Details</a>
  </div>
</div>
        </div>
    {% endfor %}
</div>
        </div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px;">
<form method="POST" enctype="multipart/form-data" class="border border-3 border-primary bg-secondary">
    {% csrf_token %}
    <div class="m-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter username">
    </div>
    <div class="m-3">
  <label class="form-label">Firstname</label>
  <input type="text" class="form-control" name="f" placeholder="Enter firstname">
    </div>
    <div class="m-3">
  <label class="form-label">Lastname</label>
  <input type="text" class="form-control" name="l" placeholder="Enter lastname">
    </div>
  <div class="m-3">
  <label class="form-label">email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter mail.id">
    </div>
  <div class="m-3">
  <label class="form-label">password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter password">
    </div>
  <div class="m-3">
  <label class="form-label"> Confirm password</label>
  <input type="password" class="form-control" name="cp" placeholder="Enter password">
    </div>
    <div class="mb-3">
  <input type="submit" value="Register" style="margin-left:15px;">
    </div>
</form>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <div>
        <h4>You have searched for <span class="text-success">"{{query}}"</span></h4>
    </div>
</center>

<div class="container-fluid mt-4" style="margin-bottom:100px;">
    <div class="row">
        {% for i in products %}
        <div class="col-sm-4">
        <div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." style="height:250px;width:100%;">
  <div class="card-body">
    <h5 class="card-title text-center">{{i.name}}</h5>
    <h5 class="card-text text-center" style="text-align:justify">{{i.price}}</h5>
    <a href="{% url 'shop:alldetails' i.slug %}" style="position:relative;left:38%" class="btn btn-primary">Details</a>
  </div>
</div>
        </div>
        {% empty %}
        <h6 class="text-center text-danger">0 Results found</h6>
    {% endfor %}
</div>
        </div>

{% endblock %}